### ISSUE TITLE
Recomended Product Missing in Category Page

### ISSUE THREAD

**Issue by massmagic85** [clerkio/clerk-prestashop#14] opened 2022-09-15 22:44 UTC
Good evening,
I have downloaded the module using the github repository and installed the zip on my prestashop... The version is 6.6.1 not officially released.
I noticed that after updating the module from 6.6.0 to 6.6.1 on category pages were missing recomanded products "Best in this category".
If i revert the module to 6.6.0 recomanded products in category page are present.

Thank you

**Comment by stubbedev** [comment] 2022-09-21 14:56
Hi Massmagic,

Which version of prestashop are you running? 

The category injection is different due to hooks not being available in 1.6, so this info would be helpful.

**Comment by massmagic85** [comment] 2022-09-21 15:39
I'm using Prestashop 1.7.8.6

**Comment by stubbedev** [comment] 2022-09-22 08:00
Hi Massmagic,

I have just tested it on the same Prestashop version and for me I still get the span element injected with the hook.

![screencapture-presta17-stubbe-dev-stagio-index-php-2022-09-22-09_57_48](https://user-images.githubusercontent.com/89036433/191690712-8d04c9e2-d354-4147-a414-ee7138494139.png)

As you can see the version is the same.

Here is a link to a category page, where we can see the category slider injected:

https://presta17.stubbe.dev/en/3-clothes

(You can search "@category-page-popular" in the HTML to find it.)

Given that setting hasn't changed, and that the versions are the same, do you think it might be related to recompiling the smarty templates after flipping the setting?

**Comment by stubbedev** [comment] 2022-09-27 07:52
I am closing for now, since I cannot reproduce the issue on the same version. 

let me know if you have more details, then I will reopen

**Closed as completed by stubbedev** 2022-09-27 07:52 UTC
